export const personalInfo = {
  name: 'Anthony Paquet',
  title: 'Engineering Leader & Cloud Architect',
  subtitle: 'FinOps • Security & Compliance • 0→1 to Scale',
  location: 'Canada, Quebec',
  phone: '418-564-6162',
  email: 'Anthonypaquet1508@gmail.com',
  tagline: 'Seasoned Engineering Leader who helps companies cut cloud costs 30–60%, pass compliance audits, and build from 0→1 to scale—without slowing your roadmap. Results in weeks.',
  summary: `Operating at the intersection of data and context, I design and scale secure, cost-optimized, and resilient systems that accelerate business outcomes. Passionate about AI-powered transformation, I take products from 0→1 to enterprise scale with strong FinOps expertise (30–60% cost reduction), compliance acceleration (SOC2, HIPAA, PCI-DSS, ISO 27001), and a DevSecOps mindset that enables teams to iterate faster and more securely. I've delivered scalable, business-aligned cloud solutions across AWS, Azure, and GCP for Financial Services, Healthcare, Media & Entertainment, and high-growth startups. Customer-obsessed, outcome-driven, with flexible engagement models to fit your needs.`,
  philosophy: 'Knowledge is the ultimate wealth — the more you share, the more it grows. I believe in continuous learning and empowering others through expertise.',
  photo: '/images/anthony-paquet.jpg',
  personal: {
    dad: 'Proud dad of two amazing boys',
    hobby: 'Avid snowboarder',
    passion: 'Technology enthusiast always exploring the cutting edge',
  },
  calendlyUrl: 'https://calendly.com/anthonypaquet1508/15min',
}

export const socialLinks = {
  linkedin: 'https://linkedin.com/in/anthony-paquet-94a31085',
  github: 'https://github.com/stonyp90',
  email: 'mailto:Anthonypaquet1508@gmail.com',
}

export const featuredProjects = [
  {
    id: 'ai-orchestrator',
    name: 'Ursly AI Edge Platform',
    tagline: 'AI Edge Orchestration for the Modern Enterprise',
    description: 'Building a next-generation AI Edge Orchestration Platform that brings intelligence to the edge. Run AI agents locally or in hybrid environments with full audit trails, enterprise identity integration, and granular access controls—all while maintaining data sovereignty and low-latency inference.',
  techStack: ['NestJS', 'React', 'TypeScript', 'Tauri', 'MongoDB', 'Keycloak', 'gRPC', 'WebSockets', 'Ollama', 'Rust'],
    githubUrl: null,
  websiteUrl: 'https://app.ursly.io',
  highlights: [
      'Edge-first AI agent deployment & orchestration',
      'Hybrid cloud/edge inference with automatic failover',
    'Full audit capabilities and compliance tracking',
      'Enterprise IDP integration (SAML, OIDC, LDAP)',
      'ReBAC & RBAC fine-grained access control',
      'Real-time agent coordination via WebSockets & gRPC',
      'Local LLM support with Ollama integration',
    ],
    icon: 'brain',
    color: 'cyber-purple',
  },
  {
    id: 'cloud-vfs',
    name: 'Ursly Cloud VFS',
    tagline: 'Universal Storage Fabric for AI Workloads',
    description: 'Building Ursly VFS—a unified virtual file system that abstracts block storage, object storage, and network protocols into a single high-performance layer. Mount any storage backend as a local filesystem with intelligent caching, encryption, and seamless multi-cloud support.',
    techStack: ['Rust', 'Tauri', 'gRPC', 'Protocol Buffers', 'FUSE', 'AWS S3', 'Azure Blob', 'GCS', 'NFS', 'SMB/CIFS'],
    githubUrl: null,
    websiteUrl: null,
    highlights: [
      'Object storage: AWS S3, Azure Blob, Google Cloud Storage',
      'Block storage: EBS, Azure Disk, Persistent Disk abstraction',
      'Network protocols: NFS v3/v4, SMB/CIFS support',
      'High-performance Rust core with zero-copy I/O',
      'Intelligent tiered caching (memory → SSD → cloud)',
      'FUSE integration for native OS filesystem mounting',
      'End-to-end encryption with key management',
      'Built for AI/ML dataset pipelines at scale',
    ],
    icon: 'cloud',
    color: 'cyber-blue',
  },
]

// Keep legacy export for compatibility
export const urslyProject = featuredProjects[0]

// Services packages for consulting
// Pricing aligned with market rates for senior cloud/security architects ($200-300/hr equivalent)
export const services = {
  finops: [
    {
      id: 'finops-program',
      name: 'FinOps Program Build',
      duration: '4–6 weeks',
      outcome: 'Complete cost governance framework with automated controls—typically delivering 30–60% savings and $200K–$1M+ annual cost avoidance.',
      deliverables: [
        'Multi-cloud cost audit & waste identification (AWS/Azure/GCP)',
        'FinOps maturity assessment & transformation roadmap',
        'Tagging taxonomy with automated enforcement',
        'Reserved/Savings Plan optimization model',
        'Chargeback/showback model & team accountability',
        'Executive dashboards & anomaly detection',
        'CI/CD cost gates & policy-as-code guardrails',
        'Team training & 90-day implementation playbook',
      ],
      notIncluded: ['Ongoing optimization sprints', 'Vendor contract negotiations', 'Organizational change management'],
      icon: 'chart',
      color: 'cyber-green',
    },
    {
      id: 'compute-cost-engineering',
      name: 'Compute Cost Engineering',
      duration: '3–4 weeks',
      outcome: 'Cut GPU, HPC, and compute-intensive workload costs by 35–55% while maintaining performance and team velocity.',
      deliverables: [
        'GPU/CPU utilization analysis & rightsizing',
        'Spot/preemptible instance strategy with failover',
        'Workload scheduling & queue optimization',
        'Autoscaling with cost ceilings & performance targets',
        'Storage & data transfer optimization',
        'Render farm / compute cluster efficiency tuning',
        'Monthly burn-rate projections & forecasting',
      ],
      notIncluded: ['Application refactoring', 'Pipeline development', 'Data engineering'],
      icon: 'brain',
      color: 'cyber-purple',
    },
  ],
  security: [
    {
      id: 'compliance-acceleration',
      name: 'Compliance Acceleration',
      duration: '5–8 weeks',
      outcome: 'Audit-ready in weeks, not months. Technical controls implemented for SOC2, ISO 27001, HIPAA, or PCI-DSS with continuous monitoring.',
      deliverables: [
        'Gap analysis & control mapping to framework',
        'Cloud security configuration (CIS benchmarks)',
        'IAM least-privilege implementation',
        'Secrets management & encryption at rest/transit',
        'Centralized logging & SIEM integration',
        'Evidence automation & continuous monitoring',
        'Auditor-ready documentation package',
        'Pre-audit dry run & remediation support',
      ],
      notIncluded: ['Audit fees', 'Policy/procedure writing', 'Penetration testing', 'Vendor assessments'],
      icon: 'lock',
      color: 'cyber-blue',
    },
    {
      id: 'data-security-governance',
      name: 'Data Security & Governance',
      duration: '4–5 weeks',
      outcome: 'Enterprise-grade data protection with automated controls—audit trails, access governance, and compliance built in from day one.',
      deliverables: [
        'Data classification & sensitivity labeling',
        'PII/PHI detection, redaction & masking automation',
        'API gateway security & rate limiting',
        'Identity & access governance (IAM, RBAC, ABAC)',
        'Data loss prevention (DLP) controls',
        'Usage monitoring, anomaly detection & alerts',
        'Compliance audit logging & reporting',
        'Data governance policy framework',
      ],
      notIncluded: ['Data migration', 'Application development', 'Master data management', 'Data quality initiatives'],
      icon: 'robot',
      color: 'cyber-purple',
    },
  ],
  dr: [
    {
      id: 'dr-architecture',
      name: 'Disaster Recovery Program',
      duration: '6–10 weeks',
      outcome: 'Battle-tested multi-region recovery that satisfies regulators, insurers, and the board with validated RTO/RPO targets.',
      deliverables: [
        'Business impact analysis & dependency mapping',
        'RTO/RPO definition by system criticality',
        'Multi-region/multi-cloud architecture design',
        'Automated IaC-based recovery orchestration',
        'Database replication & automated failover',
        'Application-tier recovery automation',
        'Comprehensive runbooks & escalation procedures',
        'Full DR simulation with stakeholder sign-off',
        'Ongoing monitoring & alerting setup',
      ],
      notIncluded: ['Ongoing DR operations', 'Third-party SaaS DR', 'Annual testing coordination'],
      icon: 'cloud',
      color: 'cyber-blue',
    },
  ],
  architecture: [
    {
      id: 'platform-foundation',
      name: 'Cloud Platform Foundation',
      duration: '6–10 weeks',
      outcome: 'Production-grade foundation built for scale, security, and operational excellence from day one—with FinOps and compliance built in.',
      deliverables: [
        'Landing zone & multi-account/project structure',
        'Enterprise IAM & identity federation (SSO)',
        'Network architecture with security zones',
        'Observability stack (logs, metrics, traces, dashboards)',
        'Security baselines & compliance controls',
        'FinOps foundations & cost visibility',
        'CI/CD reference architecture & pipelines',
        'Operations runbooks & team enablement',
      ],
      notIncluded: ['Application development', 'Data migration', 'Ongoing operations', 'Team augmentation'],
      icon: 'architecture',
      color: 'cyber-blue',
    },
    {
      id: 'devsecops-transformation',
      name: 'DevSecOps Transformation',
      duration: '4–6 weeks',
      outcome: 'Ship faster and safer—security embedded in every deployment without slowing your teams down through automated controls.',
      deliverables: [
        'Secure CI/CD pipeline architecture',
        'SAST/DAST/SCA tool integration',
        'Container & image security scanning',
        'Secrets management & rotation automation',
        'Infrastructure-as-Code with policy guardrails',
        'Security gates & approval workflows',
        'Developer security training & guidelines',
      ],
      notIncluded: ['Application remediation', 'Legacy modernization', 'Code refactoring'],
      icon: 'shield',
      color: 'cyber-purple',
    },
  ],
}

export const retainers = [
  { 
    name: 'Strategic Advisory', 
    description: 'Ongoing guidance for cloud strategy, architecture decisions, and technical leadership.',
    includes: [
      'Monthly architecture reviews',
      'Vendor & tool evaluations',
      'Technical roadmap guidance',
      'Team mentorship & training',
      'Async support via Slack/email',
    ],
  },
  { 
    name: 'Cloud Governance', 
    description: 'Continuous oversight of cost, security, and compliance with quarterly optimization sprints.',
    includes: [
      'Monthly cost & security reviews',
      'Compliance monitoring & reporting',
      'Quarterly optimization sprints',
      'Policy & guardrail updates',
      'Incident response advisory',
    ],
  },
  { 
    name: 'Fractional Architect', 
    description: 'Embedded senior leadership for hands-on delivery, team scaling, and strategic execution.',
    includes: [
      'Embedded team leadership',
      'Hands-on architecture & delivery',
      'Sprint planning & execution',
      'Hiring & team scaling support',
      'Executive reporting & updates',
    ],
  },
]

export const industries = [
  {
    name: 'Financial Services & FinTech',
    icon: 'bank',
    description: 'Multi-region DR, PCI-DSS, SOC2 for enterprise clients',
    color: 'cyber-green',
  },
  {
    name: 'Healthcare & HealthTech',
    icon: 'health',
    description: 'HIPAA compliance, PHI protection, secure patient data',
    color: 'cyber-blue',
  },
  {
    name: 'AI & SaaS (Series A–C)',
    icon: 'rocket',
    description: 'SOC2 for enterprise sales, GPU cost control, LLM security',
    color: 'cyber-purple',
  },
  {
    name: 'Defense & Government',
    icon: 'shield',
    description: 'Mission-critical systems, FedRAMP, secure deployments',
    color: 'cyber-pink',
  },
  {
    name: 'Media & Entertainment',
    icon: 'film',
    description: 'TPN/MPAA compliance, camera-to-cloud, content security',
    color: 'cyber-blue',
  },
  {
    name: 'E-commerce at Scale',
    icon: 'cart',
    description: 'PCI compliance, high availability, real-time systems',
    color: 'cyber-green',
  },
  {
    name: 'Telecommunications',
    icon: 'signal',
    description: '99.99% uptime, streaming platforms, massive scale',
    color: 'cyber-purple',
  },
  {
    name: 'IoT & Smart Systems',
    icon: 'chip',
    description: 'Secure APIs, device authentication, edge computing',
    color: 'cyber-pink',
  },
]

export const experiences = [
  {
    company: 'CREE8',
    position: 'Head of Engineering | Founding Engineer',
    location: 'California, United States',
    period: 'Previous',
    description: 'CREE8 streamlines cloud adoption, easing creator workflows through centralization, efficiency, and automation. It empowers creative teams to fully leverage cloud-native capabilities by simplifying complex processes.',
    outcomes: [
      { metric: '60%', description: 'Cloud cost reduction ($500K+ annual savings)' },
      { metric: '6 months', description: 'SOC 2 Type II + TPN Gold certifications' },
      { metric: '40%', description: 'Faster deployment through DevSecOps' },
      { metric: '10+', description: 'Senior engineers led' },
    ],
    achievements: [
      'Cut multi-cloud costs by 60% ($500K+ annually) across AWS, GCP, and Azure through FinOps optimization and architecture redesign',
      'Achieved SOC 2 Type II and TPN Gold (MPAA) certifications in 6 months—enabling enterprise studio contracts',
      'Built and scaled engineering team from 3 to 10+ senior engineers (SRE, DevOps, Full-Stack)',
      'Architected camera-to-cloud workflows securing content for 50+ distributed creative teams',
    ],
    tags: ['AWS', 'GCP', 'Azure', 'FinOps', 'SOC 2', 'TPN/MPAA', 'Media Security'],
  },
  {
    company: 'Videotron',
    position: 'Cloud Infrastructure Engineer',
    location: 'Québec, Canada',
    period: 'Previous',
    description: 'Led cloud infrastructure for one of Canada\'s largest telecommunications providers—streaming platforms serving millions of subscribers.',
    outcomes: [
      { metric: '99.9%', description: 'Uptime for mission-critical streaming' },
      { metric: 'Millions', description: 'Subscribers served' },
    ],
    achievements: [
      'Architected high-availability infrastructure handling peak traffic for live events',
      'Implemented observability stack reducing MTTR by 50%',
      'Hardened security posture across streaming and web platforms',
    ],
    tags: ['Telecommunications', 'Streaming', 'AWS', 'High Availability', 'Security'],
  },
  {
    company: 'Fairstone Bank',
    position: 'Cloud Security & DR Architect',
    location: 'Montréal, Canada',
    period: 'Previous',
    description: 'Architected disaster recovery and compliance infrastructure for a regulated Canadian financial institution.',
    outcomes: [
      { metric: '<4hr', description: 'RTO for critical banking systems' },
      { metric: '100%', description: 'Regulatory compliance maintained' },
    ],
    achievements: [
      'Designed multi-region DR architecture meeting OSFI regulatory requirements',
      'Implemented automated failover reducing RTO from 24hrs to under 4hrs',
      'Built compliance monitoring ensuring continuous regulatory adherence',
    ],
    tags: ['Financial Services', 'AWS', 'Disaster Recovery', 'Regulatory Compliance', 'OSFI'],
  },
  {
    company: 'SSENSE',
    position: 'Data Platform Engineer',
    location: 'Montréal, Canada',
    period: 'Previous',
    description: 'Built real-time data infrastructure for a $1B+ luxury e-commerce platform serving global customers.',
    outcomes: [
      { metric: 'Real-time', description: 'Customer data sync at scale' },
      { metric: '$1B+', description: 'GMV platform supported' },
    ],
    achievements: [
      'Architected real-time loyalty system handling millions of customer events',
      'Built fault-tolerant data pipelines with sub-second latency',
      'Enabled personalization driving measurable revenue impact',
    ],
    tags: ['E-commerce', 'Real-time Data', 'Cloud Architecture', 'High Scale'],
  },
  {
    company: 'Dormakaba Americas',
    position: 'API & IoT Platform Architect',
    location: 'Montréal, Canada',
    period: 'Previous',
    description: 'Designed secure API infrastructure for enterprise smart access systems deployed across commercial buildings.',
    outcomes: [
      { metric: 'Enterprise API', description: 'Third-party integration platform' },
      { metric: 'Secure', description: 'Device authentication at scale' },
    ],
    achievements: [
      'Architected public API enabling secure third-party smart lock integrations',
      'Designed device authentication handling thousands of access points',
      'Built abstraction layer reducing integration time from weeks to days',
    ],
    tags: ['IoT', 'API Security', 'Smart Access', 'Enterprise Integration'],
  },
  {
    company: 'Vanderlande',
    position: 'Cloud Platform Engineer',
    location: 'Québec, Canada',
    period: 'Previous',
    description: 'Built mission-critical airport security software deployed globally across major international airports.',
    outcomes: [
      { metric: '6 months', description: 'Zero-to-production MVP delivery' },
      { metric: 'Global', description: 'Deployed in major international airports' },
    ],
    achievements: [
      'Built PAX Divest Assistant from 0→1 in 6 months—a zero-contact screening solution launched in response to COVID-19, now operational in several major airports worldwide',
      'Architected cloud-based video assistance system enabling remote agent support at security checkpoints',
      'Developed decentralized software optimizing luggage throughput and passenger flow',
    ],
    tags: ['Cloud Software', 'Airport Systems', 'Mission-Critical', 'Global Deployment'],
    projectUrl: 'https://www.vanderlande.com/news-insights/vanderlande-introduces-new-self-service-application-for-security-checkpoints/',
  },
  {
    company: 'PetalMD',
    position: 'Healthcare Cloud Engineer',
    location: 'Québec, Canada',
    period: 'Previous',
    description: 'Built HIPAA-compliant cloud platform for healthcare scheduling serving hospitals and medical groups.',
    outcomes: [
      { metric: 'HIPAA', description: 'Fully compliant architecture' },
      { metric: '100+', description: 'Healthcare organizations served' },
    ],
    achievements: [
      'Designed HIPAA-compliant architecture protecting PHI for 100+ healthcare organizations',
      'Built real-time scheduling system reducing physician burnout',
      'Implemented audit logging and access controls meeting regulatory requirements',
    ],
    tags: ['Healthcare', 'HIPAA', 'Cloud Security', 'PHI Protection'],
  },
  {
    company: 'CGI - National Defense',
    position: 'Secure Systems Engineer',
    location: 'Québec, Canada',
    period: 'Previous',
    description: 'Developed mission-critical software for Canadian defense programs with strict security requirements.',
    outcomes: [
      { metric: 'Mission-Critical', description: 'Defense systems delivered' },
      { metric: 'Secret', description: 'Security clearance maintained' },
    ],
    achievements: [
      'Built mission-critical defense software meeting strict security and reliability standards',
      'Implemented secure CI/CD pipelines for classified environments',
      'Maintained Secret-level security clearance throughout engagement',
    ],
    tags: ['Defense', 'Government', 'Mission-Critical', 'Secure DevOps', 'Clearance'],
  },
  {
    company: 'Logical',
    position: 'Co-Founder & CTO',
    location: 'Québec, Canada',
    period: 'Founded',
    description: 'Co-founded software company delivering custom web applications.',
    outcomes: [
      { metric: 'Startup', description: 'Founded and scaled' },
    ],
    achievements: [
      'Led technical strategy and development team',
      'Delivered custom web applications for diverse clients',
    ],
    tags: ['Startup', 'CTO', 'Web Development', 'Leadership'],
  },
]

export const skills = {
  cloud: [
    { name: 'AWS', level: 95 },
    { name: 'GCP', level: 85 },
    { name: 'Azure', level: 80 },
    { name: 'Vercel', level: 35 },
    { name: 'Oracle Cloud', level: 30 },
  ],
  languages: [
    { name: 'Node.js', level: 95 },
    { name: 'TypeScript', level: 95 },
    { name: 'Python', level: 85 },
    { name: 'Go', level: 80 },
    { name: 'Rust', level: 75 },
    { name: 'Java', level: 70 },
    { name: 'Bash/Shell', level: 90 },
  ],
  devops: [
    { name: 'Kubernetes', level: 90 },
    { name: 'Docker', level: 95 },
    { name: 'CI/CD', level: 95 },
    { name: 'GitHub Actions', level: 90 },
    { name: 'Terraform', level: 90 },
    { name: 'Git', level: 95 },
  ],
  databases: [
    { name: 'SQL', level: 90 },
    { name: 'NoSQL', level: 90 },
    { name: 'PostgreSQL', level: 85 },
    { name: 'DynamoDB', level: 85 },
    { name: 'Redis', level: 80 },
    { name: 'MongoDB', level: 80 },
    { name: 'Elasticsearch', level: 85 },
  ],
  dataAnalytics: [
    { name: 'BigQuery', level: 85 },
    { name: 'Looker', level: 80 },
    { name: 'Datadog', level: 90 },
    { name: 'CloudWatch', level: 90 },
    { name: 'Grafana', level: 85 },
  ],
  frameworks: [
    { name: 'React', level: 95 },
    { name: 'Next.js', level: 90 },
    { name: 'Vue.js', level: 85 },
    { name: 'Angular', level: 75 },
    { name: 'Express', level: 90 },
    { name: 'NestJS', level: 80 },
  ],
  specialties: [
    { name: 'AI/ML', level: 85 },
    { name: 'LLM Integration', level: 90 },
    { name: 'FinOps', level: 95 },
    { name: 'DevSecOps', level: 90 },
    { name: 'Serverless', level: 90 },
    { name: 'Big Data', level: 80 },
  ],
  methodologies: [
    { name: 'Clean Architecture', level: 95 },
    { name: 'Domain-Driven Design (DDD)', level: 90 },
    { name: 'Event-Driven Systems', level: 95 },
    { name: 'Behavior-Driven Development (BDD)', level: 85 },
    { name: 'Test-Driven Development (TDD)', level: 90 },
    { name: 'Microservices', level: 95 },
    { name: 'CQRS/Event Sourcing', level: 85 },
  ],
  devsecops: [
    { name: 'Security Automation', level: 95 },
    { name: 'SAST/DAST', level: 90 },
    { name: 'Secret Management', level: 95 },
    { name: 'Compliance Automation', level: 95 },
    { name: 'SOC 2 / TPN Gold', level: 95 },
    { name: 'Vulnerability Scanning', level: 90 },
    { name: 'Zero Trust Architecture', level: 85 },
    { name: 'IAM & RBAC', level: 90 },
  ],
}

export const certifications = [
  {
    name: 'AWS Certified Solutions Architect – Associate',
    issuer: 'Amazon Web Services (AWS)',
    badgeImage: 'https://images.credly.com/size/340x340/images/0e284c3f-5164-4b21-8660-0d84737941bc/image.png',
    credlyUrl: 'https://www.credly.com/badges/34b7839a-dc9d-4183-95d7-0cc6b9d596d7/linked_in_profile',
  },
  {
    name: 'AWS Certified Developer – Associate',
    issuer: 'Amazon Web Services (AWS)',
    badgeImage: 'https://images.credly.com/size/340x340/images/b9feab85-1a43-4f6c-99a5-631b88d5461b/image.png',
    credlyUrl: 'https://www.credly.com/badges/2fc2506e-0e1c-4019-96c4-4f1fb09f5583/linked_in_profile',
  },
  {
    name: 'AWS Certified Cloud Practitioner',
    issuer: 'Amazon Web Services (AWS)',
    badgeImage: 'https://images.credly.com/size/340x340/images/00634f82-b07f-4bbd-a6bb-53de397fc3a6/image.png',
    credlyUrl: 'https://www.credly.com/badges/ba61181f-893c-4e91-be07-790f167f6835',
  },
]

export const education = {
  degree: 'Computer Science',
  institution: 'Cégep Garneau',
  period: '2008 - 2011',
  location: 'Québec, Canada',
}

export const languages = [
  { name: 'French', level: 'Native' },
  { name: 'English', level: 'Fluent' },
]

export const additionalExpertise = [
  'gRPC & Protocol Buffers',
  'GraphQL',
  'REST API Design',
  'WebSockets',
  'Message Queues (RabbitMQ, SQS, Kafka)',
  'Elasticsearch',
  'Datadog & Monitoring',
  'Security Best Practices',
  'Performance Optimization',
  'System Design',
  'Technical Leadership',
  'Agile & Scrum',
  'Code Review & Mentorship',
  'Technical Documentation',
]
