export const personalInfo = {
  name: 'Anthony Paquet',
  title: 'AI & Cloud Architect | Engineering Leader',
  subtitle: 'FinOps • Security & Compliance • 0→1 to Scale',
  location: 'Canada, Quebec',
  email: 'me@anthonypaquet.com',
  tagline: 'I help CTOs and engineering leaders cut cloud costs 30-60%, pass SOC2/HIPAA audits in weeks, and build infrastructure that scales—without slowing your roadmap.',
  summary: `I design and scale secure, cost-efficient cloud systems and take products from 0→1 to enterprise scale. Deep FinOps work cuts cloud spend, and a DevSecOps approach helps teams ship faster without sacrificing security. The result is resilient infrastructure that holds up under real load and keeps costs down.`,
  philosophy: 'Knowledge is the ultimate wealth — the more you share, the more it grows. I believe in continuous learning and empowering others through expertise.',
  photo: '/images/anthony-paquet.jpg',
  personal: {
    dad: 'Proud dad of two amazing boys',
    hobby: 'Avid snowboarder',
    passion: 'Technology enthusiast always exploring the cutting edge',
  },
  calendlyUrl: 'https://calendly.com/anthonypaquet1508/15min',
}

export const socialLinks = {
  linkedin: 'https://linkedin.com/in/anthony-paquet-94a31085',
  github: 'https://github.com/stonyp90',
  email: 'mailto:me@anthonypaquet.com',
}

// Canonical site URL + a no-AI-tells share blurb (no em-dashes/semicolons)
export const siteUrl = 'https://www.anthonypaquet.com'
export const shareText =
  'Anthony Paquet, AI & Cloud Architect. Cut cloud costs 30-60%, pass SOC2/HIPAA in weeks, scale from 0 to 1 to enterprise.'

// Services packages for consulting
// Pricing aligned with market rates for senior cloud/security architects ($200-300/hr equivalent)
export const services = {
  finops: [
    {
      id: 'finops-program',
      name: 'FinOps Program Build',
      outcome: 'Complete cost governance framework with automated controls—typically delivering 30–60% savings and significant annual cost avoidance.',
      deliverables: [
        'Multi-cloud cost audit & waste identification (AWS/Azure/GCP)',
        'FinOps maturity assessment & transformation roadmap',
        'Tagging taxonomy with automated enforcement',
        'Reserved/Savings Plan optimization model',
        'Chargeback/showback model & team accountability',
        'Executive dashboards & anomaly detection',
        'CI/CD cost gates & policy-as-code guardrails',
        'Team training & 90-day implementation playbook',
      ],
      notIncluded: ['Ongoing optimization sprints', 'Vendor contract negotiations', 'Organizational change management'],
      icon: 'chart',
      color: 'cyber-green',
    },
    {
      id: 'compute-cost-engineering',
      name: 'Compute Cost Engineering',
      outcome: 'Cut GPU, HPC, and compute-intensive workload costs by 35–55% while maintaining performance and team velocity.',
      deliverables: [
        'GPU/CPU utilization analysis & rightsizing',
        'Spot/preemptible instance strategy with failover',
        'Workload scheduling & queue optimization',
        'Autoscaling with cost ceilings & performance targets',
        'Storage & data transfer optimization',
        'Render farm / compute cluster efficiency tuning',
        'Monthly burn-rate projections & forecasting',
      ],
      notIncluded: ['Application refactoring', 'Pipeline development', 'Data engineering'],
      icon: 'brain',
      color: 'cyber-purple',
    },
  ],
  security: [
    {
      id: 'compliance-acceleration',
      name: 'Compliance Acceleration',
      outcome: 'Audit-ready in weeks, not months. Technical controls implemented for SOC2, ISO 27001, HIPAA, or PCI-DSS with continuous monitoring.',
      deliverables: [
        'Gap analysis & control mapping to framework',
        'Cloud security configuration (CIS benchmarks)',
        'IAM least-privilege implementation',
        'Secrets management & encryption at rest/transit',
        'Centralized logging & SIEM integration',
        'Evidence automation & continuous monitoring',
        'Auditor-ready documentation package',
        'Pre-audit dry run & remediation support',
      ],
      notIncluded: ['Audit fees', 'Policy/procedure writing', 'Penetration testing', 'Vendor assessments'],
      icon: 'lock',
      color: 'cyber-blue',
    },
    {
      id: 'data-security-governance',
      name: 'Data Security & Governance',
      outcome: 'Enterprise-grade data protection with automated controls—audit trails, access governance, and compliance built in from day one.',
      deliverables: [
        'Data classification & sensitivity labeling',
        'PII/PHI detection, redaction & masking automation',
        'API gateway security & rate limiting',
        'Identity & access governance (IAM, RBAC, ABAC)',
        'Data loss prevention (DLP) controls',
        'Usage monitoring, anomaly detection & alerts',
        'Compliance audit logging & reporting',
        'Data governance policy framework',
      ],
      notIncluded: ['Data migration', 'Application development', 'Master data management', 'Data quality initiatives'],
      icon: 'robot',
      color: 'cyber-purple',
    },
    {
      id: 'cloud-infrastructure-security',
      name: 'Cloud Infrastructure Security',
      outcome: 'Harden your cloud infrastructure with Zero Trust architecture, secure network access, and defense-in-depth controls—protecting your assets from modern threats.',
      deliverables: [
        'Zero Trust architecture design & implementation',
        'VPN & secure remote access setup (WireGuard, OpenVPN, cloud-native)',
        'Network segmentation & micro-segmentation',
        'Cloud firewall & WAF configuration',
        'Identity-aware proxy & conditional access',
        'Bastion hosts & privileged access management',
        'Endpoint security integration',
        'Security monitoring & threat detection',
      ],
      notIncluded: ['Physical security', 'Endpoint device management', 'Security operations (SOC)', '24/7 monitoring services'],
      icon: 'shield',
      color: 'cyber-blue',
    },
  ],
  ai: [
    {
      id: 'ai-infrastructure',
      name: 'AI Infrastructure & Eval Platforms',
      outcome: 'Production-grade infrastructure for AI agents and model evaluation. Isolated sandboxes, GPU cost control, and the platform engineering behind reliable AI products.',
      deliverables: [
        'Eval-sandbox platform with isolated microVMs, snapshot and restore',
        'Agent runtime and tool-execution environments',
        'GPU and inference cost optimization (35-55% reduction)',
        'Training and inference pipeline architecture',
        'OpenAPI-first tool and MCP server design',
        'Observability for traces, evals, and reward logic',
        'Spot and preemption resilience',
      ],
      notIncluded: ['Model training', 'Data labeling', 'Research'],
      icon: 'brain',
      color: 'cyber-purple',
    },
    {
      id: 'ai-llm-security',
      name: 'AI / LLM Security & Governance',
      outcome: 'Ship AI to production safely with LLM gateways, PII protection, prompt-injection controls, and the audit trails that pass SOC 2.',
      deliverables: [
        'LLM gateway with policy enforcement',
        'PII and PHI detection, redaction, and masking',
        'Prompt-injection and jailbreak controls',
        'Usage metering and cost ceilings',
        'Model and data access governance',
        'Compliance audit logging for AI systems',
        'Red-team and abuse testing',
      ],
      notIncluded: ['Model fine-tuning', 'Content moderation staffing', 'Legal review'],
      icon: 'lock',
      color: 'cyber-blue',
    },
    {
      id: 'ai-adoption',
      name: 'AI Adoption & Agent Engineering',
      outcome: 'Turn AI from a demo into a dependable system with agent design, evals, and tooling that move real business outcomes.',
      deliverables: [
        'Agent and workflow design for your use case',
        'Eval suites, rubrics, and grading harnesses',
        'Tool and MCP integration for your existing APIs',
        'RAG and retrieval architecture',
        'Guardrails, fallbacks, and human-in-the-loop',
        'Cost and latency tuning',
        'Team enablement and AI-assisted dev workflow',
      ],
      notIncluded: ['Foundational model research', 'Annotation services', 'Hardware procurement'],
      icon: 'robot',
      color: 'cyber-green',
    },
  ],
  architecture: [
    {
      id: 'platform-foundation',
      name: 'Cloud Platform Foundation',
      outcome: 'Production-grade foundation built for scale, security, and operational excellence from day one—with FinOps and compliance built in.',
      deliverables: [
        'Landing zone & multi-account/project structure',
        'Enterprise IAM & identity federation (SSO)',
        'Network architecture with security zones',
        'Observability stack (logs, metrics, traces, dashboards)',
        'Security baselines & compliance controls',
        'FinOps foundations & cost visibility',
        'CI/CD reference architecture & pipelines',
        'Operations runbooks & team enablement',
      ],
      notIncluded: ['Application development', 'Data migration', 'Ongoing operations', 'Team augmentation'],
      icon: 'architecture',
      color: 'cyber-blue',
    },
    {
      id: 'legacy-modernization',
      name: 'Legacy Modernization & Tech Debt',
      outcome: 'Transform legacy systems into modern, maintainable architectures—reduce technical debt, improve velocity, and unlock innovation.',
      deliverables: [
        'Technical debt assessment & prioritization',
        'Application portfolio analysis & modernization roadmap',
        'Strangler pattern & incremental migration strategy',
        'Monolith decomposition & microservices design',
        'Database modernization & migration planning',
        'API-first architecture & integration layer',
        'Automated testing & CI/CD implementation',
        'Team upskilling & knowledge transfer',
      ],
      notIncluded: ['Full application rewrite', 'Data migration execution', 'Ongoing maintenance'],
      icon: 'chart',
      color: 'cyber-green',
    },
    {
      id: 'devsecops-transformation',
      name: 'DevSecOps Transformation',
      outcome: 'Ship faster and safer—security embedded in every deployment without slowing your teams down through automated controls.',
      deliverables: [
        'Secure CI/CD pipeline architecture',
        'SAST/DAST/SCA tool integration',
        'Container & image security scanning',
        'Secrets management & rotation automation',
        'Infrastructure-as-Code with policy guardrails',
        'Security gates & approval workflows',
        'Developer security training & guidelines',
      ],
      notIncluded: ['Application remediation', 'Code refactoring', 'Legacy system updates'],
      icon: 'shield',
      color: 'cyber-purple',
    },
  ],
}

export const retainers = [
  { 
    name: 'Strategic Advisory', 
    description: 'Ongoing guidance for cloud strategy, architecture decisions, and technical leadership.',
    includes: [
      'Monthly architecture reviews',
      'Vendor & tool evaluations',
      'Technical roadmap guidance',
      'Team mentorship & training',
      'Async support via Slack/email',
    ],
  },
  { 
    name: 'Cloud Governance', 
    description: 'Continuous oversight of cost, security, and compliance with quarterly optimization sprints.',
    includes: [
      'Monthly cost & security reviews',
      'Compliance monitoring & reporting',
      'Quarterly optimization sprints',
      'Policy & guardrail updates',
      'Incident response advisory',
    ],
  },
  { 
    name: 'Fractional Architect', 
    description: 'Embedded senior leadership for hands-on delivery, team scaling, and strategic execution.',
    includes: [
      'Embedded team leadership',
      'Hands-on architecture & delivery',
      'Sprint planning & execution',
      'Hiring & team scaling support',
      'Executive reporting & updates',
    ],
  },
]

export const industries = [
  {
    name: 'Financial Services & FinTech',
    icon: 'bank',
    description: 'Multi-region DR, PCI-DSS, SOC2 for enterprise clients',
    color: 'cyber-green',
  },
  {
    name: 'Healthcare & HealthTech',
    icon: 'health',
    description: 'HIPAA compliance, PHI protection, secure patient data',
    color: 'cyber-blue',
  },
  {
    name: 'AI & SaaS (Series A–C)',
    icon: 'rocket',
    description: 'SOC2 for enterprise sales, GPU cost control, LLM security',
    color: 'cyber-purple',
  },
  {
    name: 'Defense & Government',
    icon: 'shield',
    description: 'Mission-critical systems, FedRAMP, secure deployments',
    color: 'cyber-pink',
  },
  {
    name: 'Media & Entertainment',
    icon: 'film',
    description: 'TPN/MPAA compliance, camera-to-cloud, content security',
    color: 'cyber-blue',
  },
  {
    name: 'E-commerce at Scale',
    icon: 'cart',
    description: 'PCI compliance, high availability, real-time systems',
    color: 'cyber-green',
  },
  {
    name: 'Telecommunications',
    icon: 'signal',
    description: '99.99% uptime, streaming platforms, massive scale',
    color: 'cyber-purple',
  },
  {
    name: 'IoT & Smart Systems',
    icon: 'chip',
    description: 'Secure APIs, device authentication, edge computing',
    color: 'cyber-pink',
  },
]

export const experiences = [
  {
    company: 'Bespoke Labs',
    via: 'a.team (contract)',
    position: 'Senior Cloud & Security Architect',
    location: 'Mountain View, California',
    period: 'Current',
    description: 'Series A-funded RL lab that powers the greatest models.',
    outcomes: [
      { metric: 'Horizon', description: 'RL tasks, rubrics, and evals' },
      { metric: 'Eval sandbox', description: 'Firecracker microVM platform' },
      { metric: '30%', description: 'Cloud spend reduction' },
    ],
    achievements: [
      'Built an eval-sandbox platform running AI-agent workloads in isolated Firecracker microVMs, with snapshot and restore that survives Spot preemption.',
      'Authored RL tasks, grading rubrics, and evals on Horizon, the core platform, modeling the tool environments and reward logic agents are scored against.',
      'Made key contributions to Horizon, the core RL platform, across rubrics, tasks, and evals.',
      'Cut cloud spend 30% and led SOC 2 and security compliance for the platform.',
    ],
    tags: ['Series A', 'RL Lab', 'Horizon', 'Agent Evals', 'Firecracker', 'FinOps', 'SOC 2', 'Cloud Security'],
  },
  {
    company: 'CREE8',
    position: 'Head of Engineering & Founding Engineer',
    location: 'California, United States',
    period: 'Previous',
    description: 'CREE8 streamlines cloud adoption, easing creator workflows through centralization, efficiency, and automation. It empowers creative teams to fully leverage cloud-native capabilities by simplifying complex processes.',
    outcomes: [
      { metric: '60%', description: 'Multi-cloud cost reduction' },
      { metric: '6 months', description: 'SOC 2 Type II and TPN Gold' },
      { metric: '40%', description: 'Faster iteration via DevSecOps' },
    ],
    achievements: [
      'Built and led a team of 10 senior SRE, DevOps, and Full-Stack engineers to deploy enterprise-grade cloud solutions.',
      'Achieved SOC 2 Type II and TPN Gold certifications within 6 months by implementing AI-driven compliance automation workflows.',
      'Optimized multi-cloud operations, cutting costs by 60% across AWS, GCP, and Azure through FinOps practices and architecture improvements.',
      'Pioneered camera-to-cloud workflows, improving content ingestion and collaboration among 50+ distributed creative teams.',
      'Accelerated iteration speed by 40%, strengthened system security, and boosted resilience by adopting AI and DevSecOps practices.',
    ],
    tags: ['AWS', 'GCP', 'Azure', 'FinOps', 'SOC 2', 'TPN/MPAA', 'Media Security'],
  },
  {
    company: 'Videotron',
    position: 'Senior Cloud DevOps Engineer',
    location: 'Québec, Canada',
    period: 'Previous',
    description: 'Led DevOps for websites and streaming. Deployed tools, analyzed metrics, implemented scalable infrastructure, and enhanced security, ensuring resilience and reliability.',
    outcomes: [
      { metric: 'Streaming', description: 'Web and streaming delivery' },
      { metric: 'Security', description: 'Hardened, resilient infrastructure' },
    ],
    achievements: [
      'Led DevOps for Videotron websites and streaming platforms.',
      'Deployed tooling and analyzed metrics to improve delivery and reliability.',
      'Implemented scalable infrastructure and hardened security for resilience.',
    ],
    tags: ['Telecommunications', 'Streaming', 'AWS', 'DevOps', 'Security'],
  },
  {
    company: 'Banque Fairstone',
    position: 'Senior Cloud Engineer | Contractor',
    location: 'Montréal, Canada',
    period: 'Previous',
    description: 'Led multi-region, multi-account disaster recovery on AWS and integrated monitoring tools for resilience.',
    outcomes: [
      { metric: 'Multi-region', description: 'Disaster recovery on AWS' },
      { metric: 'Resilience', description: 'Integrated monitoring' },
    ],
    achievements: [
      'Led multi-region, multi-account disaster recovery on AWS.',
      'Integrated monitoring tools to strengthen resilience and reliability.',
    ],
    tags: ['Financial Services', 'AWS', 'Disaster Recovery', 'Multi-Region', 'Monitoring'],
  },
  {
    company: 'SSENSE',
    position: 'Senior Cloud Engineer | Contractor',
    location: 'Montréal, Canada',
    period: 'Previous',
    description: 'Implemented a loyalty system via Talon One integration, synchronizing historical and real-time data for reliable, efficient data exchange with internal systems.',
    outcomes: [
      { metric: 'Real-time', description: 'Historical and live data sync' },
      { metric: 'Loyalty', description: 'Talon One integration' },
    ],
    achievements: [
      'Implemented a loyalty system through Talon One integration.',
      'Synchronized historical and real-time data for reliable exchange with internal systems.',
    ],
    tags: ['E-commerce', 'Talon One', 'Real-time Data', 'Integrations'],
  },
  {
    company: 'Dormakaba Americas',
    position: 'Senior Cloud Engineer',
    location: 'Montréal, Canada',
    period: 'Previous',
    description: 'Led design of a public API enabling third-party integration with Dormakaba. Built an abstraction layer simplifying lock configuration, enhancing client usability and developer experience in smart access deployment.',
    outcomes: [
      { metric: 'Public API', description: 'Third-party integration platform' },
      { metric: 'Smart access', description: 'Simplified lock configuration' },
    ],
    achievements: [
      'Led design of a public API enabling third-party integration with Dormakaba.',
      'Built an abstraction layer that simplified lock configuration and improved client usability.',
      'Improved developer experience for smart access deployment.',
    ],
    tags: ['IoT', 'API Design', 'Smart Access', 'Developer Experience'],
  },
  {
    company: 'Vanderlande',
    position: 'Cloud Software Developer',
    location: 'Québec, Canada',
    period: 'Previous',
    description: 'Developed the PAX Divesting Assistant, a self-service app enhancing airport checkpoint efficiency by allowing passengers to handle divestment independently. This reduces agent reliance and boosts automation, improving security and operations.',
    outcomes: [
      { metric: 'Self-service', description: 'PAX Divesting Assistant' },
      { metric: 'Airports', description: 'Checkpoint efficiency' },
    ],
    achievements: [
      'Developed the PAX Divesting Assistant, a self-service app that lets passengers handle divestment independently.',
      'Reduced agent reliance and increased automation, improving checkpoint security and operations.',
    ],
    tags: ['Airport Systems', 'Cloud Software', 'Automation', 'Security'],
  },
  {
    company: 'Vanderlande',
    position: 'Software Developer',
    location: 'Québec, Canada',
    period: 'Previous',
    description: 'Developed a decentralized software optimizing luggage throughput at airport checkpoints. Deployed globally, enhancing luggage processing efficiency and improving passenger experience and operational performance.',
    outcomes: [
      { metric: 'Global', description: 'Deployed across major airports' },
      { metric: 'Throughput', description: 'Optimized luggage processing' },
    ],
    achievements: [
      'Developed decentralized software optimizing luggage throughput at airport checkpoints.',
      'Deployed globally, improving luggage processing efficiency and passenger experience.',
    ],
    tags: ['Airport Systems', 'Distributed Systems', 'Global Deployment', 'Performance'],
  },
  {
    company: 'PetalMD',
    position: 'Software Developer',
    location: 'Québec, Canada',
    period: 'Previous',
    description: 'Developed a secure cloud platform enabling healthcare to orchestrate real-time patient care, boosting efficiency, streamlining processes, and improving outcomes.',
    outcomes: [
      { metric: 'Healthcare', description: 'Secure cloud platform' },
      { metric: 'Real-time', description: 'Patient care orchestration' },
    ],
    achievements: [
      'Developed a secure cloud platform for healthcare to orchestrate real-time patient care.',
      'Improved efficiency and streamlined clinical processes.',
    ],
    tags: ['Healthcare', 'Cloud', 'Real-time', 'Security'],
  },
  {
    company: 'CGI - National Defense',
    position: 'Software Developer and DevOps',
    location: 'Québec, Canada',
    period: 'Previous',
    description: 'Worked on a suite of services that help the military plan and make decisions.',
    outcomes: [
      { metric: 'Defense', description: 'Military decision-support services' },
      { metric: 'DevOps', description: 'Secure delivery' },
    ],
    achievements: [
      'Worked on a suite of services helping the military plan and make decisions.',
      'Contributed across development and DevOps for secure delivery.',
    ],
    tags: ['Defense', 'Government', 'DevOps', 'Secure Delivery'],
  },
  {
    company: 'Logicale',
    position: 'Co-Founder and CTO',
    location: 'Québec, Canada',
    period: 'Founded',
    description: 'Software company designing and developing custom web applications.',
    outcomes: [
      { metric: 'Co-founder', description: 'Custom web applications' },
    ],
    achievements: [
      'Co-founded a software company building custom web applications.',
      'Led technical direction and delivery for client projects.',
    ],
    tags: ['Startup', 'CTO', 'Web Development', 'Leadership'],
  },
]

export const skills = {
  cloud: [
    { name: 'AWS', level: 95 },
    { name: 'GCP', level: 85 },
    { name: 'Azure', level: 80 },
    { name: 'Vercel', level: 35 },
    { name: 'Oracle Cloud', level: 30 },
  ],
  languages: [
    { name: 'Node.js', level: 95 },
    { name: 'TypeScript', level: 95 },
    { name: 'Python', level: 85 },
    { name: 'Go', level: 80 },
    { name: 'Rust', level: 75 },
    { name: 'Java', level: 70 },
    { name: 'Bash/Shell', level: 90 },
  ],
  devops: [
    { name: 'Kubernetes', level: 90 },
    { name: 'Docker', level: 95 },
    { name: 'CI/CD', level: 95 },
    { name: 'GitHub Actions', level: 90 },
    { name: 'Terraform', level: 90 },
    { name: 'Git', level: 95 },
  ],
  databases: [
    { name: 'SQL', level: 90 },
    { name: 'NoSQL', level: 90 },
    { name: 'PostgreSQL', level: 85 },
    { name: 'DynamoDB', level: 85 },
    { name: 'Redis', level: 80 },
    { name: 'MongoDB', level: 80 },
    { name: 'Elasticsearch', level: 85 },
  ],
  dataAnalytics: [
    { name: 'BigQuery', level: 85 },
    { name: 'Looker', level: 80 },
    { name: 'Datadog', level: 90 },
    { name: 'CloudWatch', level: 90 },
    { name: 'Grafana', level: 85 },
  ],
  frameworks: [
    { name: 'React', level: 95 },
    { name: 'Next.js', level: 90 },
    { name: 'Vue.js', level: 85 },
    { name: 'Angular', level: 75 },
    { name: 'Express', level: 90 },
    { name: 'NestJS', level: 80 },
  ],
  specialties: [
    { name: 'AI/ML', level: 85 },
    { name: 'LLM Integration', level: 90 },
    { name: 'FinOps', level: 95 },
    { name: 'DevSecOps', level: 90 },
    { name: 'Serverless', level: 90 },
    { name: 'Big Data', level: 80 },
  ],
  methodologies: [
    { name: 'Clean Architecture', level: 95 },
    { name: 'Domain-Driven Design (DDD)', level: 90 },
    { name: 'Event-Driven Systems', level: 95 },
    { name: 'Behavior-Driven Development (BDD)', level: 85 },
    { name: 'Test-Driven Development (TDD)', level: 90 },
    { name: 'Microservices', level: 95 },
    { name: 'CQRS/Event Sourcing', level: 85 },
  ],
  devsecops: [
    { name: 'Security Automation', level: 95 },
    { name: 'SAST/DAST', level: 90 },
    { name: 'Secret Management', level: 95 },
    { name: 'Compliance Automation', level: 95 },
    { name: 'SOC 2 / TPN Gold', level: 95 },
    { name: 'Vulnerability Scanning', level: 90 },
    { name: 'Zero Trust Architecture', level: 95 },
    { name: 'IAM & RBAC', level: 90 },
  ],
}

export const certifications = [
  {
    name: 'AWS Certified Solutions Architect – Associate',
    issuer: 'Amazon Web Services (AWS)',
    badgeImage: 'https://images.credly.com/size/340x340/images/0e284c3f-5164-4b21-8660-0d84737941bc/image.png',
  },
  {
    name: 'AWS Certified Developer – Associate',
    issuer: 'Amazon Web Services (AWS)',
    badgeImage: 'https://images.credly.com/size/340x340/images/b9feab85-1a43-4f6c-99a5-631b88d5461b/image.png',
  },
  {
    name: 'AWS Certified Cloud Practitioner',
    issuer: 'Amazon Web Services (AWS)',
    badgeImage: 'https://images.credly.com/size/340x340/images/00634f82-b07f-4bbd-a6bb-53de397fc3a6/image.png',
  },
]

export const education = {
  degree: 'Computer Science',
  institution: 'Cégep Garneau',
  period: '2008 - 2011',
  location: 'Québec, Canada',
}

export const languages = [
  { name: 'French', level: 'Native' },
  { name: 'English', level: 'Fluent' },
]

export const additionalExpertise = [
  'gRPC & Protocol Buffers',
  'GraphQL',
  'REST API Design',
  'WebSockets',
  'Message Queues (RabbitMQ, SQS, Kafka)',
  'Elasticsearch',
  'Datadog & Monitoring',
  'Security Best Practices',
  'Zero Trust Architecture',
  'VPN & Secure Access',
  'Network Security',
  'Performance Optimization',
  'System Design',
  'Technical Leadership',
  'Agile & Scrum',
  'Code Review & Mentorship',
  'Technical Documentation',
]
